// <auto-generated />
using System;
using TeamRegistrationApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TeamRegistrationApi.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250508210734_CreateMatchResultsTable")]
    partial class CreateMatchResultsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LeaderboardAPI.Models.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MatchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
